### ISSUE TITLE
command to train and which file is the main entry point

### ISSUE THREAD

**Issue by jpainam** [zenght/scene_attribute_MP#1]
Hi; thank you for sharing your code: I would like to know which file then contains the main entry point? Or which file should I run to get the results you reported in your paper.

Thank you

**Comment by zenght** [comment]
Sorry, it took so long to reply to your question.  To obtain the reported results, firstly, the features generated from different CNN should be obtained, and input into the **Message_passing_encoding.py**. It may take a long time to train to get the results I reported.
